
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import JSZip from 'https://esm.sh/jszip@3.10.1';
import { Artifact, Session } from '../types';

export const exportArtifactAsZip = async (artifact: Artifact, session: Session) => {
    const zip = new JSZip();
    const safeTitle = session.prompt.slice(0, 20).replace(/[^a-z0-9]/gi, '_');
    const folderName = `dashgen-${safeTitle}-${Date.now()}`;
    const folder = zip.folder(folderName);

    if (!folder) return;

    // 1. index.html
    folder.file("index.html", artifact.html);

    // 2. README.md
    const readmeContent = `# DashGen Generated Project

## Overview
**Prompt:** "${session.prompt}"
**Style:** ${artifact.styleName}
**Generated:** ${new Date().toLocaleString()}

## How to Run
You can serve this file using any static file server.

### Using Python
\`\`\`bash
python3 -m http.server
\`\`\`

### Using Node.js (npx)
\`\`\`bash
npx serve .
\`\`\`

## Edit
Open \`index.html\` in your favorite code editor (VS Code, Cursor, etc.) to modify the structure.
`;
    folder.file("README.md", readmeContent);

    // 3. package.json
    const packageJson = {
        name: folderName.toLowerCase(),
        version: "1.0.0",
        description: "Dashboard generated by DashGen Pro",
        scripts: {
            "start": "npx serve ."
        },
        dependencies: {
            "serve": "^14.0.0"
        }
    };
    folder.file("package.json", JSON.stringify(packageJson, null, 2));

    // Generate and Download
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement("a");
    a.href = url;
    a.download = `${folderName}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};
